os: linux

language: go

go:
  - 1.13.x

script:
  # Test the code
  - go test -v ./...
  # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -o demo
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t mrckurz/demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag mrckurz/demo:latest mrckurz/demo:$GIT_SHA
  - docker push mrckurz/demo:latest
  - docker push mrckurz/demo:$GIT_SHA

services:
- docker
